<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: usage.proto

namespace Toggly\FeatureManagement\Telemetry\Pb\Usage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The request message containing the user's name.
 *
 * Generated from protobuf message <code>Usage.FeatureStat</code>
 */
class FeatureStat extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string appKey = 1;</code>
     */
    protected $appKey = '';
    /**
     * Generated from protobuf field <code>string environment = 2;</code>
     */
    protected $environment = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp time = 3;</code>
     */
    protected $time = null;
    /**
     * Generated from protobuf field <code>repeated .Usage.StatMessage stats = 4;</code>
     */
    private $stats;
    /**
     * Generated from protobuf field <code>int32 totalUniqueUsers = 5;</code>
     */
    protected $totalUniqueUsers = 0;
    /**
     * Generated from protobuf field <code>optional string instanceName = 6;</code>
     */
    protected $instanceName = null;
    /**
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp processStartTime = 7;</code>
     */
    protected $processStartTime = null;
    /**
     * Generated from protobuf field <code>optional string appVersion = 8;</code>
     */
    protected $appVersion = null;
    /**
     * Application-level unique user ID hashes (all users, regardless of feature usage)
     *
     * Generated from protobuf field <code>repeated int32 uniqueUserHashes = 9;</code>
     */
    private $uniqueUserHashes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $appKey
     *     @type string $environment
     *     @type \Google\Protobuf\Timestamp $time
     *     @type \Toggly\FeatureManagement\Telemetry\Pb\Usage\StatMessage[] $stats
     *     @type int $totalUniqueUsers
     *     @type string $instanceName
     *     @type \Google\Protobuf\Timestamp $processStartTime
     *     @type string $appVersion
     *     @type int[] $uniqueUserHashes
     *           Application-level unique user ID hashes (all users, regardless of feature usage)
     * }
     */
    public function __construct($data = NULL) {
        \Toggly\FeatureManagement\Telemetry\Pb\GPBMetadata\Usage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string appKey = 1;</code>
     * @return string
     */
    public function getAppKey()
    {
        return $this->appKey;
    }

    /**
     * Generated from protobuf field <code>string appKey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAppKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->appKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string environment = 2;</code>
     * @return string
     */
    public function getEnvironment()
    {
        return $this->environment;
    }

    /**
     * Generated from protobuf field <code>string environment = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEnvironment($var)
    {
        GPBUtil::checkString($var, True);
        $this->environment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp time = 3;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getTime()
    {
        return $this->time;
    }

    public function hasTime()
    {
        return isset($this->time);
    }

    public function clearTime()
    {
        unset($this->time);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp time = 3;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Usage.StatMessage stats = 4;</code>
     * @return RepeatedField<\Toggly\FeatureManagement\Telemetry\Pb\Usage\StatMessage>
     */
    public function getStats()
    {
        return $this->stats;
    }

    /**
     * Generated from protobuf field <code>repeated .Usage.StatMessage stats = 4;</code>
     * @param \Toggly\FeatureManagement\Telemetry\Pb\Usage\StatMessage[] $var
     * @return $this
     */
    public function setStats($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Toggly\FeatureManagement\Telemetry\Pb\Usage\StatMessage::class);
        $this->stats = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 totalUniqueUsers = 5;</code>
     * @return int
     */
    public function getTotalUniqueUsers()
    {
        return $this->totalUniqueUsers;
    }

    /**
     * Generated from protobuf field <code>int32 totalUniqueUsers = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalUniqueUsers($var)
    {
        GPBUtil::checkInt32($var);
        $this->totalUniqueUsers = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string instanceName = 6;</code>
     * @return string
     */
    public function getInstanceName()
    {
        return isset($this->instanceName) ? $this->instanceName : '';
    }

    public function hasInstanceName()
    {
        return isset($this->instanceName);
    }

    public function clearInstanceName()
    {
        unset($this->instanceName);
    }

    /**
     * Generated from protobuf field <code>optional string instanceName = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setInstanceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->instanceName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp processStartTime = 7;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getProcessStartTime()
    {
        return $this->processStartTime;
    }

    public function hasProcessStartTime()
    {
        return isset($this->processStartTime);
    }

    public function clearProcessStartTime()
    {
        unset($this->processStartTime);
    }

    /**
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp processStartTime = 7;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setProcessStartTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->processStartTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string appVersion = 8;</code>
     * @return string
     */
    public function getAppVersion()
    {
        return isset($this->appVersion) ? $this->appVersion : '';
    }

    public function hasAppVersion()
    {
        return isset($this->appVersion);
    }

    public function clearAppVersion()
    {
        unset($this->appVersion);
    }

    /**
     * Generated from protobuf field <code>optional string appVersion = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setAppVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->appVersion = $var;

        return $this;
    }

    /**
     * Application-level unique user ID hashes (all users, regardless of feature usage)
     *
     * Generated from protobuf field <code>repeated int32 uniqueUserHashes = 9;</code>
     * @return RepeatedField<int>
     */
    public function getUniqueUserHashes()
    {
        return $this->uniqueUserHashes;
    }

    /**
     * Application-level unique user ID hashes (all users, regardless of feature usage)
     *
     * Generated from protobuf field <code>repeated int32 uniqueUserHashes = 9;</code>
     * @param int[] $var
     * @return $this
     */
    public function setUniqueUserHashes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->uniqueUserHashes = $arr;

        return $this;
    }

}

