<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: usage.proto

namespace Toggly\FeatureManagement\Telemetry\Pb\Usage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Usage.StatMessage</code>
 */
class StatMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string feature = 1;</code>
     */
    protected $feature = '';
    /**
     * Legacy: use variantStats instead
     *
     * Generated from protobuf field <code>int32 enabledCount = 2 [deprecated = true];</code>
     * @deprecated
     */
    protected $enabledCount = 0;
    /**
     * Legacy: use variantStats instead
     *
     * Generated from protobuf field <code>int32 disabledCount = 3 [deprecated = true];</code>
     * @deprecated
     */
    protected $disabledCount = 0;
    /**
     *Ex: unique username, IP address
     *
     * Generated from protobuf field <code>int32 uniqueContextIdentifierEnabledCount = 4;</code>
     */
    protected $uniqueContextIdentifierEnabledCount = 0;
    /**
     * Generated from protobuf field <code>int32 uniqueContextIdentifierDisabledCount = 5;</code>
     */
    protected $uniqueContextIdentifierDisabledCount = 0;
    /**
     * Legacy: use variantStats instead
     *
     * Generated from protobuf field <code>int32 uniqueRequestEnabledCount = 6 [deprecated = true];</code>
     * @deprecated
     */
    protected $uniqueRequestEnabledCount = 0;
    /**
     * Legacy: use variantStats instead
     *
     * Generated from protobuf field <code>int32 uniqueRequestDisabledCount = 7 [deprecated = true];</code>
     * @deprecated
     */
    protected $uniqueRequestDisabledCount = 0;
    /**
     * Legacy: use variantStats instead
     *
     * Generated from protobuf field <code>int32 usedCount = 8 [deprecated = true];</code>
     * @deprecated
     */
    protected $usedCount = 0;
    /**
     * Generated from protobuf field <code>int32 uniqueUsersUsedCount = 9;</code>
     */
    protected $uniqueUsersUsedCount = 0;
    /**
     * Unique user ID hashes for "used" tracking (aggregated per feature via Redis → VM)
     *
     * Generated from protobuf field <code>repeated int32 uniqueUserHashes = 10;</code>
     */
    private $uniqueUserHashes;
    /**
     * Multi-variate support - all new metrics should use this
     *
     * Generated from protobuf field <code>map<string, .Usage.VariantStats> variantStats = 11;</code>
     */
    private $variantStats;
    /**
     * Unique user tracking for "viewed" metric (per feature, not per variant)
     *
     * Generated from protobuf field <code>repeated int32 uniqueViewedUserHashes = 12;</code>
     */
    private $uniqueViewedUserHashes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $feature
     *     @type int $enabledCount
     *           Legacy: use variantStats instead
     *     @type int $disabledCount
     *           Legacy: use variantStats instead
     *     @type int $uniqueContextIdentifierEnabledCount
     *          Ex: unique username, IP address
     *     @type int $uniqueContextIdentifierDisabledCount
     *     @type int $uniqueRequestEnabledCount
     *           Legacy: use variantStats instead
     *     @type int $uniqueRequestDisabledCount
     *           Legacy: use variantStats instead
     *     @type int $usedCount
     *           Legacy: use variantStats instead
     *     @type int $uniqueUsersUsedCount
     *     @type int[] $uniqueUserHashes
     *           Unique user ID hashes for "used" tracking (aggregated per feature via Redis → VM)
     *     @type array|\Google\Protobuf\Internal\MapField $variantStats
     *           Multi-variate support - all new metrics should use this
     *     @type int[] $uniqueViewedUserHashes
     *           Unique user tracking for "viewed" metric (per feature, not per variant)
     * }
     */
    public function __construct($data = NULL) {
        \Toggly\FeatureManagement\Telemetry\Pb\GPBMetadata\Usage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string feature = 1;</code>
     * @return string
     */
    public function getFeature()
    {
        return $this->feature;
    }

    /**
     * Generated from protobuf field <code>string feature = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFeature($var)
    {
        GPBUtil::checkString($var, True);
        $this->feature = $var;

        return $this;
    }

    /**
     * Legacy: use variantStats instead
     *
     * Generated from protobuf field <code>int32 enabledCount = 2 [deprecated = true];</code>
     * @return int
     * @deprecated
     */
    public function getEnabledCount()
    {
        if ($this->enabledCount !== 0) {
            @trigger_error('enabledCount is deprecated.', E_USER_DEPRECATED);
        }
        return $this->enabledCount;
    }

    /**
     * Legacy: use variantStats instead
     *
     * Generated from protobuf field <code>int32 enabledCount = 2 [deprecated = true];</code>
     * @param int $var
     * @return $this
     * @deprecated
     */
    public function setEnabledCount($var)
    {
        @trigger_error('enabledCount is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkInt32($var);
        $this->enabledCount = $var;

        return $this;
    }

    /**
     * Legacy: use variantStats instead
     *
     * Generated from protobuf field <code>int32 disabledCount = 3 [deprecated = true];</code>
     * @return int
     * @deprecated
     */
    public function getDisabledCount()
    {
        if ($this->disabledCount !== 0) {
            @trigger_error('disabledCount is deprecated.', E_USER_DEPRECATED);
        }
        return $this->disabledCount;
    }

    /**
     * Legacy: use variantStats instead
     *
     * Generated from protobuf field <code>int32 disabledCount = 3 [deprecated = true];</code>
     * @param int $var
     * @return $this
     * @deprecated
     */
    public function setDisabledCount($var)
    {
        @trigger_error('disabledCount is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkInt32($var);
        $this->disabledCount = $var;

        return $this;
    }

    /**
     *Ex: unique username, IP address
     *
     * Generated from protobuf field <code>int32 uniqueContextIdentifierEnabledCount = 4;</code>
     * @return int
     */
    public function getUniqueContextIdentifierEnabledCount()
    {
        return $this->uniqueContextIdentifierEnabledCount;
    }

    /**
     *Ex: unique username, IP address
     *
     * Generated from protobuf field <code>int32 uniqueContextIdentifierEnabledCount = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setUniqueContextIdentifierEnabledCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->uniqueContextIdentifierEnabledCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 uniqueContextIdentifierDisabledCount = 5;</code>
     * @return int
     */
    public function getUniqueContextIdentifierDisabledCount()
    {
        return $this->uniqueContextIdentifierDisabledCount;
    }

    /**
     * Generated from protobuf field <code>int32 uniqueContextIdentifierDisabledCount = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setUniqueContextIdentifierDisabledCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->uniqueContextIdentifierDisabledCount = $var;

        return $this;
    }

    /**
     * Legacy: use variantStats instead
     *
     * Generated from protobuf field <code>int32 uniqueRequestEnabledCount = 6 [deprecated = true];</code>
     * @return int
     * @deprecated
     */
    public function getUniqueRequestEnabledCount()
    {
        if ($this->uniqueRequestEnabledCount !== 0) {
            @trigger_error('uniqueRequestEnabledCount is deprecated.', E_USER_DEPRECATED);
        }
        return $this->uniqueRequestEnabledCount;
    }

    /**
     * Legacy: use variantStats instead
     *
     * Generated from protobuf field <code>int32 uniqueRequestEnabledCount = 6 [deprecated = true];</code>
     * @param int $var
     * @return $this
     * @deprecated
     */
    public function setUniqueRequestEnabledCount($var)
    {
        @trigger_error('uniqueRequestEnabledCount is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkInt32($var);
        $this->uniqueRequestEnabledCount = $var;

        return $this;
    }

    /**
     * Legacy: use variantStats instead
     *
     * Generated from protobuf field <code>int32 uniqueRequestDisabledCount = 7 [deprecated = true];</code>
     * @return int
     * @deprecated
     */
    public function getUniqueRequestDisabledCount()
    {
        if ($this->uniqueRequestDisabledCount !== 0) {
            @trigger_error('uniqueRequestDisabledCount is deprecated.', E_USER_DEPRECATED);
        }
        return $this->uniqueRequestDisabledCount;
    }

    /**
     * Legacy: use variantStats instead
     *
     * Generated from protobuf field <code>int32 uniqueRequestDisabledCount = 7 [deprecated = true];</code>
     * @param int $var
     * @return $this
     * @deprecated
     */
    public function setUniqueRequestDisabledCount($var)
    {
        @trigger_error('uniqueRequestDisabledCount is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkInt32($var);
        $this->uniqueRequestDisabledCount = $var;

        return $this;
    }

    /**
     * Legacy: use variantStats instead
     *
     * Generated from protobuf field <code>int32 usedCount = 8 [deprecated = true];</code>
     * @return int
     * @deprecated
     */
    public function getUsedCount()
    {
        if ($this->usedCount !== 0) {
            @trigger_error('usedCount is deprecated.', E_USER_DEPRECATED);
        }
        return $this->usedCount;
    }

    /**
     * Legacy: use variantStats instead
     *
     * Generated from protobuf field <code>int32 usedCount = 8 [deprecated = true];</code>
     * @param int $var
     * @return $this
     * @deprecated
     */
    public function setUsedCount($var)
    {
        @trigger_error('usedCount is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkInt32($var);
        $this->usedCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 uniqueUsersUsedCount = 9;</code>
     * @return int
     */
    public function getUniqueUsersUsedCount()
    {
        return $this->uniqueUsersUsedCount;
    }

    /**
     * Generated from protobuf field <code>int32 uniqueUsersUsedCount = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setUniqueUsersUsedCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->uniqueUsersUsedCount = $var;

        return $this;
    }

    /**
     * Unique user ID hashes for "used" tracking (aggregated per feature via Redis → VM)
     *
     * Generated from protobuf field <code>repeated int32 uniqueUserHashes = 10;</code>
     * @return RepeatedField<int>
     */
    public function getUniqueUserHashes()
    {
        return $this->uniqueUserHashes;
    }

    /**
     * Unique user ID hashes for "used" tracking (aggregated per feature via Redis → VM)
     *
     * Generated from protobuf field <code>repeated int32 uniqueUserHashes = 10;</code>
     * @param int[] $var
     * @return $this
     */
    public function setUniqueUserHashes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->uniqueUserHashes = $arr;

        return $this;
    }

    /**
     * Multi-variate support - all new metrics should use this
     *
     * Generated from protobuf field <code>map<string, .Usage.VariantStats> variantStats = 11;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getVariantStats()
    {
        return $this->variantStats;
    }

    /**
     * Multi-variate support - all new metrics should use this
     *
     * Generated from protobuf field <code>map<string, .Usage.VariantStats> variantStats = 11;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setVariantStats($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Toggly\FeatureManagement\Telemetry\Pb\Usage\VariantStats::class);
        $this->variantStats = $arr;

        return $this;
    }

    /**
     * Unique user tracking for "viewed" metric (per feature, not per variant)
     *
     * Generated from protobuf field <code>repeated int32 uniqueViewedUserHashes = 12;</code>
     * @return RepeatedField<int>
     */
    public function getUniqueViewedUserHashes()
    {
        return $this->uniqueViewedUserHashes;
    }

    /**
     * Unique user tracking for "viewed" metric (per feature, not per variant)
     *
     * Generated from protobuf field <code>repeated int32 uniqueViewedUserHashes = 12;</code>
     * @param int[] $var
     * @return $this
     */
    public function setUniqueViewedUserHashes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->uniqueViewedUserHashes = $arr;

        return $this;
    }

}

