<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metrics.proto

namespace Toggly\FeatureManagement\Telemetry\Pb\Metrics;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The request message containing the metric.
 *
 * Generated from protobuf message <code>Metrics.MetricStat</code>
 */
class MetricStat extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string appKey = 1;</code>
     */
    protected $appKey = '';
    /**
     * Generated from protobuf field <code>string environment = 2;</code>
     */
    protected $environment = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp time = 3;</code>
     */
    protected $time = null;
    /**
     * Generated from protobuf field <code>repeated .Metrics.MetricStatMessage stats = 4;</code>
     */
    private $stats;
    /**
     * Generated from protobuf field <code>repeated .Metrics.MetricCounterMessage counters = 5;</code>
     */
    private $counters;
    /**
     * Generated from protobuf field <code>repeated .Metrics.MetricObservationMessage observations = 6;</code>
     */
    private $observations;
    /**
     * Generated from protobuf field <code>optional string instanceName = 7;</code>
     */
    protected $instanceName = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $appKey
     *     @type string $environment
     *     @type \Google\Protobuf\Timestamp $time
     *     @type \Toggly\FeatureManagement\Telemetry\Pb\Metrics\MetricStatMessage[] $stats
     *     @type \Toggly\FeatureManagement\Telemetry\Pb\Metrics\MetricCounterMessage[] $counters
     *     @type \Toggly\FeatureManagement\Telemetry\Pb\Metrics\MetricObservationMessage[] $observations
     *     @type string $instanceName
     * }
     */
    public function __construct($data = NULL) {
        \Toggly\FeatureManagement\Telemetry\Pb\GPBMetadata\Metrics::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string appKey = 1;</code>
     * @return string
     */
    public function getAppKey()
    {
        return $this->appKey;
    }

    /**
     * Generated from protobuf field <code>string appKey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAppKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->appKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string environment = 2;</code>
     * @return string
     */
    public function getEnvironment()
    {
        return $this->environment;
    }

    /**
     * Generated from protobuf field <code>string environment = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEnvironment($var)
    {
        GPBUtil::checkString($var, True);
        $this->environment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp time = 3;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getTime()
    {
        return $this->time;
    }

    public function hasTime()
    {
        return isset($this->time);
    }

    public function clearTime()
    {
        unset($this->time);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp time = 3;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Metrics.MetricStatMessage stats = 4;</code>
     * @return RepeatedField<\Toggly\FeatureManagement\Telemetry\Pb\Metrics\MetricStatMessage>
     */
    public function getStats()
    {
        return $this->stats;
    }

    /**
     * Generated from protobuf field <code>repeated .Metrics.MetricStatMessage stats = 4;</code>
     * @param \Toggly\FeatureManagement\Telemetry\Pb\Metrics\MetricStatMessage[] $var
     * @return $this
     */
    public function setStats($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Toggly\FeatureManagement\Telemetry\Pb\Metrics\MetricStatMessage::class);
        $this->stats = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Metrics.MetricCounterMessage counters = 5;</code>
     * @return RepeatedField<\Toggly\FeatureManagement\Telemetry\Pb\Metrics\MetricCounterMessage>
     */
    public function getCounters()
    {
        return $this->counters;
    }

    /**
     * Generated from protobuf field <code>repeated .Metrics.MetricCounterMessage counters = 5;</code>
     * @param \Toggly\FeatureManagement\Telemetry\Pb\Metrics\MetricCounterMessage[] $var
     * @return $this
     */
    public function setCounters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Toggly\FeatureManagement\Telemetry\Pb\Metrics\MetricCounterMessage::class);
        $this->counters = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Metrics.MetricObservationMessage observations = 6;</code>
     * @return RepeatedField<\Toggly\FeatureManagement\Telemetry\Pb\Metrics\MetricObservationMessage>
     */
    public function getObservations()
    {
        return $this->observations;
    }

    /**
     * Generated from protobuf field <code>repeated .Metrics.MetricObservationMessage observations = 6;</code>
     * @param \Toggly\FeatureManagement\Telemetry\Pb\Metrics\MetricObservationMessage[] $var
     * @return $this
     */
    public function setObservations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Toggly\FeatureManagement\Telemetry\Pb\Metrics\MetricObservationMessage::class);
        $this->observations = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string instanceName = 7;</code>
     * @return string
     */
    public function getInstanceName()
    {
        return isset($this->instanceName) ? $this->instanceName : '';
    }

    public function hasInstanceName()
    {
        return isset($this->instanceName);
    }

    public function clearInstanceName()
    {
        unset($this->instanceName);
    }

    /**
     * Generated from protobuf field <code>optional string instanceName = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setInstanceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->instanceName = $var;

        return $this;
    }

}

