<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metrics.proto

namespace Toggly\FeatureManagement\Telemetry\Pb\Metrics;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Metrics.MetricStatMessage</code>
 */
class MetricStatMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string metric = 1;</code>
     */
    protected $metric = '';
    /**
     *total count for metric if feature is not specified, otherwise metric count when feature is enabled
     *
     * Generated from protobuf field <code>int32 enabledCount = 2 [deprecated = true];</code>
     * @deprecated
     */
    protected $enabledCount = 0;
    /**
     *optional metric count when feature is disabled
     *
     * Generated from protobuf field <code>int32 disabledCount = 3 [deprecated = true];</code>
     * @deprecated
     */
    protected $disabledCount = 0;
    /**
     *optional feature referenced for subcount
     *
     * Generated from protobuf field <code>optional string feature = 4;</code>
     */
    protected $feature = null;
    /**
     *value for metric if feature is not specified, otherwise value when feature is enabled
     *
     * Generated from protobuf field <code>double value = 5 [deprecated = true];</code>
     * @deprecated
     */
    protected $value = 0.0;
    /**
     *value when feature is disabled
     *
     * Generated from protobuf field <code>optional double valueDisabled = 6 [deprecated = true];</code>
     * @deprecated
     */
    protected $valueDisabled = null;
    /**
     * Multi-variate support - Key: variant name (e.g., "enabled", "control", "variant_a"), Value: metric value
     *
     * Generated from protobuf field <code>map<string, double> variantValues = 7;</code>
     */
    private $variantValues;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $metric
     *     @type int $enabledCount
     *          total count for metric if feature is not specified, otherwise metric count when feature is enabled
     *     @type int $disabledCount
     *          optional metric count when feature is disabled
     *     @type string $feature
     *          optional feature referenced for subcount
     *     @type float $value
     *          value for metric if feature is not specified, otherwise value when feature is enabled
     *     @type float $valueDisabled
     *          value when feature is disabled
     *     @type array|\Google\Protobuf\Internal\MapField $variantValues
     *           Multi-variate support - Key: variant name (e.g., "enabled", "control", "variant_a"), Value: metric value
     * }
     */
    public function __construct($data = NULL) {
        \Toggly\FeatureManagement\Telemetry\Pb\GPBMetadata\Metrics::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string metric = 1;</code>
     * @return string
     */
    public function getMetric()
    {
        return $this->metric;
    }

    /**
     * Generated from protobuf field <code>string metric = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMetric($var)
    {
        GPBUtil::checkString($var, True);
        $this->metric = $var;

        return $this;
    }

    /**
     *total count for metric if feature is not specified, otherwise metric count when feature is enabled
     *
     * Generated from protobuf field <code>int32 enabledCount = 2 [deprecated = true];</code>
     * @return int
     * @deprecated
     */
    public function getEnabledCount()
    {
        if ($this->enabledCount !== 0) {
            @trigger_error('enabledCount is deprecated.', E_USER_DEPRECATED);
        }
        return $this->enabledCount;
    }

    /**
     *total count for metric if feature is not specified, otherwise metric count when feature is enabled
     *
     * Generated from protobuf field <code>int32 enabledCount = 2 [deprecated = true];</code>
     * @param int $var
     * @return $this
     * @deprecated
     */
    public function setEnabledCount($var)
    {
        @trigger_error('enabledCount is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkInt32($var);
        $this->enabledCount = $var;

        return $this;
    }

    /**
     *optional metric count when feature is disabled
     *
     * Generated from protobuf field <code>int32 disabledCount = 3 [deprecated = true];</code>
     * @return int
     * @deprecated
     */
    public function getDisabledCount()
    {
        if ($this->disabledCount !== 0) {
            @trigger_error('disabledCount is deprecated.', E_USER_DEPRECATED);
        }
        return $this->disabledCount;
    }

    /**
     *optional metric count when feature is disabled
     *
     * Generated from protobuf field <code>int32 disabledCount = 3 [deprecated = true];</code>
     * @param int $var
     * @return $this
     * @deprecated
     */
    public function setDisabledCount($var)
    {
        @trigger_error('disabledCount is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkInt32($var);
        $this->disabledCount = $var;

        return $this;
    }

    /**
     *optional feature referenced for subcount
     *
     * Generated from protobuf field <code>optional string feature = 4;</code>
     * @return string
     */
    public function getFeature()
    {
        return isset($this->feature) ? $this->feature : '';
    }

    public function hasFeature()
    {
        return isset($this->feature);
    }

    public function clearFeature()
    {
        unset($this->feature);
    }

    /**
     *optional feature referenced for subcount
     *
     * Generated from protobuf field <code>optional string feature = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFeature($var)
    {
        GPBUtil::checkString($var, True);
        $this->feature = $var;

        return $this;
    }

    /**
     *value for metric if feature is not specified, otherwise value when feature is enabled
     *
     * Generated from protobuf field <code>double value = 5 [deprecated = true];</code>
     * @return float
     * @deprecated
     */
    public function getValue()
    {
        if ($this->value !== 0.0) {
            @trigger_error('value is deprecated.', E_USER_DEPRECATED);
        }
        return $this->value;
    }

    /**
     *value for metric if feature is not specified, otherwise value when feature is enabled
     *
     * Generated from protobuf field <code>double value = 5 [deprecated = true];</code>
     * @param float $var
     * @return $this
     * @deprecated
     */
    public function setValue($var)
    {
        @trigger_error('value is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkDouble($var);
        $this->value = $var;

        return $this;
    }

    /**
     *value when feature is disabled
     *
     * Generated from protobuf field <code>optional double valueDisabled = 6 [deprecated = true];</code>
     * @return float
     * @deprecated
     */
    public function getValueDisabled()
    {
        if (isset($this->valueDisabled)) {
            @trigger_error('valueDisabled is deprecated.', E_USER_DEPRECATED);
        }
        return isset($this->valueDisabled) ? $this->valueDisabled : 0.0;
    }

    public function hasValueDisabled()
    {
        if (isset($this->valueDisabled)) {
            @trigger_error('valueDisabled is deprecated.', E_USER_DEPRECATED);
        }
        return isset($this->valueDisabled);
    }

    public function clearValueDisabled()
    {
        @trigger_error('valueDisabled is deprecated.', E_USER_DEPRECATED);
        unset($this->valueDisabled);
    }

    /**
     *value when feature is disabled
     *
     * Generated from protobuf field <code>optional double valueDisabled = 6 [deprecated = true];</code>
     * @param float $var
     * @return $this
     * @deprecated
     */
    public function setValueDisabled($var)
    {
        @trigger_error('valueDisabled is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkDouble($var);
        $this->valueDisabled = $var;

        return $this;
    }

    /**
     * Multi-variate support - Key: variant name (e.g., "enabled", "control", "variant_a"), Value: metric value
     *
     * Generated from protobuf field <code>map<string, double> variantValues = 7;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getVariantValues()
    {
        return $this->variantValues;
    }

    /**
     * Multi-variate support - Key: variant name (e.g., "enabled", "control", "variant_a"), Value: metric value
     *
     * Generated from protobuf field <code>map<string, double> variantValues = 7;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setVariantValues($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->variantValues = $arr;

        return $this;
    }

}

