<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: usage.proto

namespace Toggly\FeatureManagement\Telemetry\Pb\Usage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Usage.StatResult</code>
 */
class StatResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 featureCount = 1;</code>
     */
    protected $featureCount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $featureCount
     * }
     */
    public function __construct($data = NULL) {
        \Toggly\FeatureManagement\Telemetry\Pb\GPBMetadata\Usage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 featureCount = 1;</code>
     * @return int
     */
    public function getFeatureCount()
    {
        return $this->featureCount;
    }

    /**
     * Generated from protobuf field <code>int32 featureCount = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFeatureCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->featureCount = $var;

        return $this;
    }

}

