<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: usage.proto

namespace Toggly\FeatureManagement\Telemetry\Pb\Usage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Usage.VariantStats</code>
 */
class VariantStats extends \Google\Protobuf\Internal\Message
{
    /**
     * Number of times this variant was checked
     *
     * Generated from protobuf field <code>int32 checkCount = 1;</code>
     */
    protected $checkCount = 0;
    /**
     * Unique requests for this variant
     *
     * Generated from protobuf field <code>int32 requestCount = 2;</code>
     */
    protected $requestCount = 0;
    /**
     * Number of times this variant was used
     *
     * Generated from protobuf field <code>int32 usedCount = 3;</code>
     */
    protected $usedCount = 0;
    /**
     * NEW: Number of times this variant was viewed
     *
     * Generated from protobuf field <code>int32 viewedCount = 4;</code>
     */
    protected $viewedCount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $checkCount
     *           Number of times this variant was checked
     *     @type int $requestCount
     *           Unique requests for this variant
     *     @type int $usedCount
     *           Number of times this variant was used
     *     @type int $viewedCount
     *           NEW: Number of times this variant was viewed
     * }
     */
    public function __construct($data = NULL) {
        \Toggly\FeatureManagement\Telemetry\Pb\GPBMetadata\Usage::initOnce();
        parent::__construct($data);
    }

    /**
     * Number of times this variant was checked
     *
     * Generated from protobuf field <code>int32 checkCount = 1;</code>
     * @return int
     */
    public function getCheckCount()
    {
        return $this->checkCount;
    }

    /**
     * Number of times this variant was checked
     *
     * Generated from protobuf field <code>int32 checkCount = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCheckCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->checkCount = $var;

        return $this;
    }

    /**
     * Unique requests for this variant
     *
     * Generated from protobuf field <code>int32 requestCount = 2;</code>
     * @return int
     */
    public function getRequestCount()
    {
        return $this->requestCount;
    }

    /**
     * Unique requests for this variant
     *
     * Generated from protobuf field <code>int32 requestCount = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRequestCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->requestCount = $var;

        return $this;
    }

    /**
     * Number of times this variant was used
     *
     * Generated from protobuf field <code>int32 usedCount = 3;</code>
     * @return int
     */
    public function getUsedCount()
    {
        return $this->usedCount;
    }

    /**
     * Number of times this variant was used
     *
     * Generated from protobuf field <code>int32 usedCount = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setUsedCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->usedCount = $var;

        return $this;
    }

    /**
     * NEW: Number of times this variant was viewed
     *
     * Generated from protobuf field <code>int32 viewedCount = 4;</code>
     * @return int
     */
    public function getViewedCount()
    {
        return $this->viewedCount;
    }

    /**
     * NEW: Number of times this variant was viewed
     *
     * Generated from protobuf field <code>int32 viewedCount = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setViewedCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->viewedCount = $var;

        return $this;
    }

}

